name: navigate_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2
  firebase_analytics: ^11.0.0
  get_it: ^7.7.0
  firebase_crashlytics: ^4.0.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
