// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9hUiIG075MYCsmlZg25kuWQ70FE6rdgo',
    appId: '1:489010922080:web:1f52d22ab91639fce3b905',
    messagingSenderId: '489010922080',
    projectId: 'fir-assignment-5509e',
    authDomain: 'fir-assignment-5509e.firebaseapp.com',
    storageBucket: 'fir-assignment-5509e.appspot.com',
    measurementId: 'G-2FE45DH6KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi6QD6AcoEOC0E_2ti6aEi9u0XX4plFA0',
    appId: '1:489010922080:android:970bbf20028734f8e3b905',
    messagingSenderId: '489010922080',
    projectId: 'fir-assignment-5509e',
    storageBucket: 'fir-assignment-5509e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxP1fqTgndQ6TDnybYti8c5GknLsStwp0',
    appId: '1:489010922080:ios:6a9271cb9198dba0e3b905',
    messagingSenderId: '489010922080',
    projectId: 'fir-assignment-5509e',
    storageBucket: 'fir-assignment-5509e.appspot.com',
    iosBundleId: 'com.example.navigateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxP1fqTgndQ6TDnybYti8c5GknLsStwp0',
    appId: '1:489010922080:ios:6a9271cb9198dba0e3b905',
    messagingSenderId: '489010922080',
    projectId: 'fir-assignment-5509e',
    storageBucket: 'fir-assignment-5509e.appspot.com',
    iosBundleId: 'com.example.navigateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9hUiIG075MYCsmlZg25kuWQ70FE6rdgo',
    appId: '1:489010922080:web:8fdd8f72a83203b3e3b905',
    messagingSenderId: '489010922080',
    projectId: 'fir-assignment-5509e',
    authDomain: 'fir-assignment-5509e.firebaseapp.com',
    storageBucket: 'fir-assignment-5509e.appspot.com',
    measurementId: 'G-877GXJMDWR',
  );

}